### PR TITLE
added homework

### PR DESCRIPTION
**Pull request by AncutaIoan**

### CODE REVIEW

**Comment by AncutaIoan** [comment]
Still work in progress, can't figure out why it wont work

**Comment by george-123** [comment]
> Still work in progress, can't figure out why it wont work

Any news?

**Comment by AncutaIoan** [comment]
Forgot to push, will do in the morning

**Review by george-123 — APPROVED** [review]

**Comment by AncutaIoan** [comment]
It was working, I`m just dumb, just got home and checked

**Pull request merged**
